# Copyright (c) 2023-present Plane Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

# Django imports
from django.db import models

# Module imports
from .base import BaseModel


class ActivityReport(BaseModel):
    """Global Agile/activity report generated by LLM (e.g. DeepSeek). Visible to all users."""

    title = models.CharField(max_length=255, blank=True, default="")
    content = models.TextField(verbose_name="Report content (plain text)")
    period_from = models.DateField(null=True, blank=True)
    period_to = models.DateField(null=True, blank=True)
    workspace = models.ForeignKey(
        "db.Workspace",
        on_delete=models.SET_NULL,
        related_name="activity_reports",
        null=True,
        blank=True,
    )
    project = models.ForeignKey(
        "db.Project",
        on_delete=models.SET_NULL,
        related_name="activity_reports",
        null=True,
        blank=True,
    )

    class Meta:
        db_table = "activity_reports"
        ordering = ("-created_at",)
        verbose_name = "Activity Report"
        verbose_name_plural = "Activity Reports"
